
FROM selenium/standalone-chrome

LABEL version="1.0" name="selenium/standalone-chrome"

#RUN rm /usr/share/nginx/html/*
#COPY socialoptin/html/ /usr/share/nginx/html/

#RUN chown www-data:www-data -R /usr/share/nginx/html

#EXPOSE 80